[workspace]

members = [
  "moolah-core",
]

[workspace.package]
version = "0.1.0"
edition = "2021"
authors = ["Ryan Crisanti"]
license-file = "LICENSE"
readme = "README.md"

[workspace.dependencies]
tracing = "0.1.37"
thiserror = "1.0.37"
chrono = "0.4"
anyhow = "1.0.66"
